# Generated by Django 5.1.4 on 2025-01-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_steps_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('fb', models.URLField(verbose_name='Facebook')),
                ('ig', models.URLField(verbose_name='Instagram')),
                ('tt', models.URLField(verbose_name='TikTok')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.AddField(
            model_name='steps',
            name='name_des',
            field=models.CharField(default=1, max_length=255, verbose_name='Тема описания'),
            preserve_default=False,
        ),
    ]
