# Generated by Django 5.1.4 on 2025-01-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_steps_description2_steps_title2'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='description2l',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steps',
            name='descriptionl',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steps',
            name='name_desl',
            field=models.CharField(default=1, max_length=255, verbose_name='Тема описания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steps',
            name='numl',
            field=models.CharField(default=1, max_length=255, verbose_name='Нумерация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steps',
            name='title2l',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steps',
            name='titlel',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
