# Generated by Django 5.1.4 on 2025-01-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='questions',
            field=models.CharField(default=1, max_length=255, verbose_name='Вопрос'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faq',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
